postgres:
  image: postgres:11.4
  container_name: orm
  ports:
    - "5432:5432"
  volumes:
    - postgres_data:/var/lib/postgresql
  environment:
    - POSTGRES_USER=orm
    - POSTGRES_PASSWORD=orm
    - POSTGRES_DB=orm
  restart: always